version: '3'

volumes:
  city_postgres:
    external:
      true

services:
  postgres:
    image: postgres:10
    ports:
    - 5432:5432
    env_file:
    - config.env
    volumes:
    - city_postgres:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - 6379:6379
    env_file:
      - config.env