# Generated by Django 2.1.2 on 2018-10-08 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [('rbac', '0001_initial'), ('rbac', '0002_auto_20181004_1556'), ('rbac', '0003_auto_20181008_0917'),
                ('rbac', '0004_auto_20181008_1221'), ('rbac', '0005_auto_20181008_1228')]

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupToRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzony')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Zmodyfikowany')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
            options={
                'verbose_name': 'Grupa do roli',
                'verbose_name_plural': 'Grupy do ról',
            },
        ),
        migrations.CreateModel(
            name='PermissionToRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzony')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Zmodyfikowany')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
            ],
            options={
                'verbose_name': 'Uprawnienie do roli',
                'verbose_name_plural': 'Uprawnienia do ról',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzony')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Zmodyfikowany')),
                ('name', models.CharField(max_length=512, unique=True, verbose_name='Nazwa')),
                ('active', models.BooleanField(default=True, verbose_name='Aktywna')),
            ],
            options={
                'verbose_name': 'Rola',
                'verbose_name_plural': 'Role',
            },
        ),
        migrations.CreateModel(
            name='UserToRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzony')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Zmodyfikowany')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.Role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Użytkownik do roli',
                'verbose_name_plural': 'Użytkownicy do ról',
            },
        ),
        migrations.AddField(
            model_name='permissiontorole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.Role'),
        ),
        migrations.AddField(
            model_name='grouptorole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.Role'),
        ),
        migrations.AlterUniqueTogether(
            name='permissiontorole',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='grouptorole',
            unique_together={('role', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='usertorole',
            unique_together={('role', 'user')},
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Nazwa'),
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzony')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Zmodyfikowany')),
                ('name', models.CharField(max_length=64, verbose_name='Nazwa')),
                ('codename', models.CharField(max_length=100, verbose_name='Akcja')),
            ],
            options={
                'verbose_name': 'Akcja',
                'verbose_name_plural': 'Akcje',
            },
        ),
        migrations.RemoveField(
            model_name='permissiontorole',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='permissiontorole',
            name='role',
        ),
        migrations.DeleteModel(
            name='PermissionToRole',
        ),
        migrations.AlterUniqueTogether(
            name='action',
            unique_together={('name', 'codename')},
        ),
        migrations.CreateModel(
            name='ActionToGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzony')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Zmodyfikowany')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.Action')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
            options={
                'verbose_name': 'Uprawnienie do grupy',
                'verbose_name_plural': 'Uprawnienia do grup',
            },
        ),
        migrations.CreateModel(
            name='ActionToRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzony')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Zmodyfikowany')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.Action')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.Role')),
            ],
            options={
                'verbose_name': 'Uprawnienie do roli',
                'verbose_name_plural': 'Uprawnienia do ról',
            },
        ),
        migrations.AlterUniqueTogether(
            name='actiontorole',
            unique_together={('role', 'action')},
        ),
    ]
