# Generated by Django 2.1.2 on 2018-10-04 13:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grouptorole',
            unique_together={('role', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='usertorole',
            unique_together={('role', 'user')},
        ),
    ]
