# Generated by Django 2.1.2 on 2018-10-08 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('rbac', '0001_squashed_0005_auto_20181008_1228'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='actiontogroup',
            unique_together={('group', 'action')},
        ),
    ]
