# Generated by Django 2.1.2 on 2018-10-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rbac', '0003_auto_20181008_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzony')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Zmodyfikowany')),
                ('name', models.CharField(max_length=64, verbose_name='Nazwa')),
                ('codename', models.CharField(max_length=100, verbose_name='Akcja')),
            ],
            options={
                'verbose_name': 'Akcja',
                'verbose_name_plural': 'Akcje',
            },
        ),
        migrations.AlterUniqueTogether(
            name='permissiontorole',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='permissiontorole',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='permissiontorole',
            name='role',
        ),
        migrations.DeleteModel(
            name='PermissionToRole',
        ),
        migrations.AlterUniqueTogether(
            name='action',
            unique_together={('name', 'codename')},
        ),
    ]
