# Generated by Django 2.1.2 on 2018-10-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_auto_20181009_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=100, verbose_name='Akcja')),
                ('group', models.CharField(blank=True, max_length=80, null=True, verbose_name='Grupa')),
                ('name', models.CharField(max_length=64, verbose_name='Nazwa')),
            ],
        ),
    ]
