# Generated by Django 2.1.2 on 2018-10-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_permissionupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='codename',
            field=models.CharField(max_length=100, unique=True, verbose_name='Akcja'),
        ),
        migrations.AlterUniqueTogether(
            name='action',
            unique_together=set(),
        ),
    ]
